/* Database schema to keep the structure of entire database. */

CREATE TABLE animals( 
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1), 
    name                 VARCHAR(50), 
    date_of_birth        date, 
    escape_attempts     INT, 
    neutered            boolean, 
    weight_kg           DEC,
    );
    
    ALTER TABLE animals ADD species VARCHAR(50);
